### ISSUE TITLE
Explosão de Erros Falso Positivo "Nenhuma resposta encontrada"

### ISSUE THREAD

**Issue by marlinhares** [pengovbr/mod-sei-resposta#62]
**Descreva o erro**

Atualmente a principal integração a usar o módulo será o Protocolo Digital
A solução Protocolo Digital ficará periodicamente consultando o SUPER, perguntando se a resposta para determinado protocolo foi feita.

A cada consulta feita, caso não haja resposta o módulo está gerando um erro, informando que Nenhuma resposta foi encontrada.

Isso vai gerar centenas de erros na infra->log.

Essa ação não se trata de erro, trata-se apenas que não existe uma resposta. Portanto não pode explodir erro ai.
Deve responder para o caller apenas um array vazio, ou nulo ou string vazia (manter o mesmo padrão atual, caso retorne um array com as respostas, então deve retornar um array vazio, qd n tiver resposta)

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Acione via soapui o serviço listarResposta do webservice sob um protocolo sem resposta

-----

**Comportamento esperado**

ver acima

-----

**Screenshots**
NA

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Ambiente: super.pd.teste.processoeletronico.gov.br
 - Versão do sistema: 1.2.2
 - Navegador: NA
 - Perfil do Usuário: NA

-----

**Informações adicionais**
Linhas que geram erro

https://github.com/supergovbr/mod-sei-resposta/blob/88bed6fe350428883b4c5d99e8eccf29b18d8ec3/src/ws/MdRespostaWS.php#L192-L203

-----
**Log de Erros**
```
Web Service:
Nenhuma resposta encontrada.

Detalhes:
MdRespostaWS

SoapFault exception: [Client] Nenhuma resposta encontrada. in /opt/infra/infra_php/InfraWS.php:106
Stack trace:
#0 /opt/sei/web/modulos/mod-sei-resposta/ws/MdRespostaWS.php(201): InfraWS->processarExcecao(Object(InfraException))
#1 /opt/sei/web/modulos/mod-sei-resposta/ws/MdRespostaWS.php(56): MdRespostaWS->listarRespostaMonitorado(Object(stdClass))
#2 [internal function]: MdRespostaWS->__call('listarResposta', Array)
#3 /opt/sei/web/modulos/mod-sei-resposta/ws/MdRespostaWS.php(311): SoapServer->handle()
#4 {main}

Trace:
#0 /opt/sei/web/modulos/mod-sei-resposta/ws/MdRespostaWS.php(201): InfraWS->processarExcecao(Object(InfraException))
#1 /opt/sei/web/modulos/mod-sei-resposta/ws/MdRespostaWS.php(56): MdRespostaWS->listarRespostaMonitorado(Object(stdClass))
#2 [internal function]: MdRespostaWS->__call('listarResposta', Array)
#3 /opt/sei/web/modulos/mod-sei-resposta/ws/MdRespostaWS.php(311): SoapServer->handle()
#4 {main}

```

**Comment by Mauro1706** [comment]
Evidência de listagem bem sucedida em com nenhum item por id invalido
https://github.com/pengovbr/mod-sei-resposta/assets/83025710/9f2974ee-aff8-4168-a3b5-2496f5843fd0
